---
- hosts: ada
  user: root

  tasks:
    # Tareas por defecto
    - include: default.yml

    # Cambia el hostname
    - include: cambia-hostname.yml base_hostname=ada

    # Operaciones generales de informática
    - include: informatica.yml

    # Operaciones específicas de las aulas de informática
    - include: aulas-informatica.yml

    # Usuarios
    - include: users/smx1a.yml
    - include: users/smx2c.yml
#    - include: users/blender.yml
    - name: Borrado del usuario Blender
      action: user name=blender state=absent remove=yes


    # Instalación de paquetes
#    - name: General | Instalación de paquetes
#      action: apt pkg={{ item }} state=installed
#      with_items:
#        - bluefish
