---
- hosts: aif
  user: root

  tasks:
    # Tareas por defecto
    - include: /home/vcarceler/playbooks/default.yml

    # Alta de usuarios (mkpasswd --method=sha-512)
    - include: /home/vcarceler/playbooks/aif-users.yml

    # Cambia el hostname
    - include: /home/vcarceler/playbooks/cambia-hostname.yml base_hostname=aig

    # Instala y configura Telegraf
    - include: telegraf.yml

    # Operaciones específicas de las aulas de informática
    - include: aulas-informatica.yml

    # Borro el usuario admin
    - include: del-admin-user.yml

    # Descarga de una imagen de owncloud
    - name: Crea el directorio /usr/share/data
      file:
        path: /usr/share/data
        state: directory

    - name: Descarga de imagen de owncloud
      get_url:
        url: http://cloud.elpuig.xeill.net/index.php/s/K98Mznnox6380Xc/download
        dest: /usr/share/data/Windows-10.ova

    # Actualiza a la última versión
    - name: Actualiza a la última versión
      action: apt pkg={{ item }} state=latest update_cache=yes
      with_items:
        - firefox
        - firefox-locale-ca

    # Instalación de paquetes
    - name: General | Instalación de paquetes
      action: apt pkg={{ item }} state=installed
      with_items:
        - cryptsetup
        - ekiga
        - openshot
        - blender
        - shutter
        - gnome-web-photo
        - hugin
        - audacity
        - wine
        - p7zip-rar
        - libreoffice-l10n-es
        - myspell-es
        - aspell-es
        - nautilus-image-converter
        - vlc
        - klavaro
        - ktouch
        - kazam
        - winff
        - gnome-system-tools
        - normalize-audio
        - id3v2
        - qtgain
        - gnome-subtitles
        - soundconverter
        - virtualbox-ext-pack
        - korganizer
        - kde-l10n-es
        - kde-l10n-ca
        - chromium-browser
        - libreoffice-base
        - libreoffice-base-drivers
        - libreoffice-report-builder
        - pdftk
        - rst2pdf
        - python-pypdf2
        - python3-pypdf2
    # Desinstala paquetes
#    - name: Quitamos paquetes (chromium)
#      action: apt pkg={{ item }} state=absent
#      with_items:
#        - chromium-browser
