---
- hosts: snowden
  user: root

  tasks:
    # Reinicia el password de los usuarios mati y tarda
    - name: Restaura la contraseña de 'mati' (mkpasswd --method=sha-512)
      action: user name=mati password="$6$N5Va1IaSlx$qbV224SeQlKxURpLwJLSPp/.DN40MI8rERQ/RUAsNe/Ha1r0h5Q7GgsxBx5WYgPpwECcaza5G5T.gnTMbjURR/"
    - name: Restaura la contraseña de 'tarda' (mkpasswd --method=sha-512)
      action: user name=tarda password="$6$LztIjxxy2$LR27HIzLZGRAwGpMv1n1lHpstOwXEKBLkJ6DPimjXE4rUf.QETHAt6EsuG8UV1Pk4cdLxhZ5enA6RKwuPiOxF."
