---
- hosts: dpt-cat
  user: root

  tasks:
    # Tareas por defecto
    - include: /home/vcarceler/playbooks/default.yml

    # Cambia el hostname
    - include: /home/vcarceler/playbooks/cambia-hostname.yml base_hostname=dptcat

    # Operaciones generales de informática
    - include: /home/vcarceler/playbooks/informatica.yml

    # Alta de usuarios
    - include: users/tecno/bguarne.yml
    - include: users/tecno/carlesgil.yml
    - include: users/tecno/carmesanchez.yml
    - include: users/tecno/germafornetcanet.yml
    - include: users/tecno/mpiro.yml
    - include: users/tecno/oespanol.yml
