---
- hosts: tesla
  user: root

  tasks:
    # Tareas por defecto
    - include: /home/vcarceler/playbooks/default.yml

    # Cambia el hostname
    - include: /home/vcarceler/playbooks/cambia-hostname.yml base_hostname=tesla

    # Operaciones generales de informática
    - include: /home/vcarceler/playbooks/informatica.yml

    # Operaciones específicas de las aulas de informática
    - include: aulas-informatica.yml

    # Usuarios ESO
    - include: users/franja2.yml
    - include: users/optativa.yml
    - include: users/3a.yml
    - include: users/3b.yml
    - include: users/3c.yml
    - include: users/3d.yml
    - include: users/informatica.yml
    - include: users/dam2a.yml
    - include: users/porrinofernando.yml
    - include: users/robotica.yml

    # Usuarios AiG
    - include: /home/vcarceler/playbooks/aif-users.yml

    # Instalación para modelio
#    - name: General | Instalación de paquetes
#      action: apt pkg={{ item }} state=installed
#      with_items:
#        - libwebkitgtk-1.0-0
#        - freecad
#        - openscad
#        - inkscape
#        - blender
#        - pgadmin3
#        - git-all
#        - kicad
#        - kicad-doc-es
