---
- hosts: 192.168.14.122
  user: root

  tasks:
    # Tareas por defecto
    - include: /home/vcarceler/playbooks/default.yml
    # Alta de usuarios (mkpasswd --method=sha-512)
    - include: /home/vcarceler/playbooks/aif-users.yml
    - include: /home/vcarceler/playbooks/default-users.yml
    # Instalación de paquetes
    - name: General | Instalación de paquetes
      action: apt pkg={{ item }} state=installed
      with_items:
        - ekiga
        - openshot
        - blender
        - shutter
        - gnome-web-photo
        - hugin
        - audacity
        - wine
        - p7zip-rar
        - libreoffice-l10n-es
        - myspell-es
        - aspell-es
        - nautilus-image-converter
        - vlc
        - klavaro
        - ktouch
        - kazam
        - winff
        - gnome-system-tools
        - normalize-audio
        - id3v2
        - qtgain
        - gnome-subtitles
        - soundconverter
        - chromium-browser
        - virtualbox-ext-pack
