---
- hosts: turing
  user: root

  tasks:
    # Tareas por defecto
    - include: /home/vcarceler/playbooks/default.yml

    # Cambia el hostname
    - include: /home/vcarceler/playbooks/cambia-hostname.yml base_hostname=turing

    # Alta de usuarios (mkpasswd --method=sha-512)
    #- include: /home/vcarceler/playbooks/turing-users.yml

    # Operaciones generales de informática
    - include: /home/vcarceler/playbooks/informatica.yml

    # Operaciones específicas de las aulas de informática
    - include: aulas-informatica.yml

    # Usuarios
    - include: users/smx1b.yml
    - include: users/asix2.yml

    # Instalación de paquetes
#    - name: General | Instalación de paquetes
#      action: apt pkg={{ item }} state=installed
#      with_items:
#        - bluefish
